class AppStrings {
  static String appname = "Medicalapp",
      bestDocapp = "Best Doctor\n Appointment Appn",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow = '''Sign up now and start exploring 
  all that our app has to offer.''',
      email = "Email",
      emailHint = "Enter your email... ",
      password = "Password",
      welcome = "Welcome",
      search = "Search doctor",
      passwordHint = "Enter your password here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forgot Password?",
      login = "Login",
      category = "Category",
      doctor = "Doctor Login",
      settings = "Settings",
      body = "Body",
      signup = "Signup",
      alreadyHaveAccount = "Account have an account?",
      ear = "Ear",
      eye = "Eye",
      liver = "Liver",
      lungs = " lungs",
      heart = "Heart ",
      kendy = "kendy",
      changePassword = "Change Password",
      termsAndCondition = "Terma and Conditions",
      signout = "Sighn Out",
      dontHaveAccount = "Don't have an account?";
}
